# SELECT
#     CAR_ID,
#     IF(SUM(START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16") = 0 , "대여중", "대여 가능") AVAILABILITY
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY
#     CAR_ID
# ORDER BY
#     CAR_ID DESC
# ;

SELECT
    CAR_ID,
    IF(SUM(START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE) = 0, '대여 가능', '대여중') AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
ORDER BY
    CAR_ID DESC
;