-- 코드를 입력하세
/*
서로 다른 table에서 컬럼이 같을 때(중복) = > 결합
INNER 조인
*/

SELECT 
B.TITLE, 
B.BOARD_ID, 
R.REPLY_ID, 
R.WRITER_ID, 
R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY AS R
JOIN USED_GOODS_BOARD AS B ON R.BOARD_ID = B.BOARD_ID
WHERE b.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
/*WHERE DATE_FORMAT(B.CREATED_DATE, "%Y-%m") = "2022-10" */
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

