SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS 1Q
JOIN
    ICECREAM_INFO AS INFO
ON
    1Q.FLAVOR = INFO.FLAVOR
GROUP BY
    INGREDIENT_TYPE    
ORDER BY
    TOTAL_ORDER ASC
;

# SELECT COUNT(FLAVOR)
#     FROM ICECREAM_INFO

# SELECT FLAVOR
#     FROM FIRST_HALF

# SELECT *
#     FROM FIRST_HALF