WITH T AS(
    SELECT 
        REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        ADDRESS
    FROM
        REST_INFO
    WHERE
        ADDRESS LIKE "서울%"
)

SELECT 
    REST_ID,
    T.REST_NAME,
    T.FOOD_TYPE,
    T.FAVORITES,
    T.ADDRESS,
    ROUND(AVG(REVIEW_SCORE) , 2) SCORE
FROM
    REST_REVIEW
JOIN
    T USING (REST_ID)
WHERE
    (REST_ID) IN (SELECT REST_ID FROM T)
GROUP BY
    REST_ID
ORDER BY
    SCORE DESC, FAVORITES DESC
;